const PORT = '6882'
const ROOT =
      location.href.indexOf('localhost') > 0 ? 'http://localhost:' : 'http://reuvenliran.hopto.org:'
export const ROOT_URL = ROOT + PORT + '/'
export const ROOT_URL_API = ROOT_URL + 'api'
export const BASE_COLOR1 = '#192d50'
export const HEADER_FONT_COLOR = '#dfceba'
export const BASE_COLOR2 = '#dfceba'
export const BASE_COLOR3 = '#f7f6f7'
export const TABLE_HEADER_FONT_COLOR = '#4f6073'
export const TABLE_FONT_COLOR = '#030b15'
